version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO

loggers:
  fastapi:
    level: INFO
    handlers: [console]
    propagate: no

  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no

  aab-api:  # Your custom logger (for modules)
    level: DEBUG
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console]
